version: "3.8"
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5078:5078"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=PlatformWellDB;User=sa;Password=ABCD1234abcd1234!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5078
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "ABCD1234abcd1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
